---
spring:
  jpa:
    hibernate.ddl-auto: update
    show_sql: false
---
# Local profile used for labtop demo
spring.profiles: local
spring:
  datasource:
    url: jdbc:h2:mem:DEMO
    username: sa
    password:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console

