apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cloud-docker-build
  name: docker-build
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/cmoullia/docker-build
