apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-docker-build
  name: docker-build
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  - name: 9779-tcp
    port: 9779
    protocol: TCP
    targetPort: 9779
  selector:
    app: cloud-docker-build
    deploymentconfig: docker-build
  sessionAffinity: None
  type: ClusterIP